name: Deploy Hugo Site

inputs:
  hugo-version:
    description: "hugo version"
    required: false
    default: "0.144.2"
  github-token-path:
    description: "1password path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  onepass-token:
    description: "1password connect token"
    required: true
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ inputs.hugo-version }}
        extended: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies & Build
      shell: bash
      run: |
        npm ci
        hugo --minify

    - name: Configure 1Password Service Account
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get Personal Token
      id: get-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ steps.get-token.outputs.token }}
        publish_branch: gh-pages
        publish_dir: ./public
