name: Semantic Release (Node)
inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "20"
  github-token-path:
    description: "The path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  onepass-token:
    description: "1password connect token"
    required: true

# ===========================================================================
# Required Permission
#permissions:
#  contents: read
# ===========================================================================

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version}}

    - name: Setup 1Password
      uses: ./.github/actions/setup-1password
      with:
        onepass-token: ${{ inputs.onepass-token }}

    - name: Get Bot Token
      id: get-token
      uses: ./.github/actions/load-github-token
      with:
        secret-path: ${{ inputs.github-token-path }}

    - name: Install & Build
      shell: bash
      run: |
        npm ci
        npm run build

    - name: Semantic Release
      shell: bash
      run: npx semantic-release@21.0.2
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
