name: Upload Notes to Dify Knowledge Base
description: "Create a new Hugo blog and push it to the target repo"
inputs:
  onepass-token:
    description: "A access-token for 1password authorsation"
    required: true
  dify-url:
    description: "Host URL of Dify Server"
    required: true
  target_dir_path:
    description: "The dir path where notes are located"
    required: true
  python-version:
    description: "Python Version"
    required: false
    default: "3.11"
  poetry-version:
    description: "Poetry Version"
    required: false
    default: "2.1.4"
  github-token-path:
    description: "1Password Secret Path of GitHub PAT"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  github-dify-repo-token:
    description: "1Password Secret Path of GitHub PAT"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  dify-api-token:
    description: "1Password Secret Path of Dify API token"
    required: false
    default: "op://DevOps/Dify - API Secret key/credential"
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Fetch release information
      id: release
      shell: bash
      run: |
        echo "RELEASE_SUBJECT=${{ inputs.release-subject }}" >> $GITHUB_ENV
        echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
        echo "${{ inputs.release-body }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "RELEASE_URL=${{ inputs.release-url }}" >> $GITHUB_ENV

    - name: Setup 1Password
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get Personal Token
      id: get-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Get Dify Repo Token
      id: get-home-stone-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-dify-repo-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Get Dify API Token
      id: get-dify-api-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.dify-api-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Get Cloud Token Username
      id: get-cloud-username
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: "op://DevOps/CloudFlare - Service Token/username"
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Get Cloud Token Cred
      id: get-cloud-cred
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: "op://DevOps/CloudFlare - Service Token/credential"
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Set up Python & Poetry
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-poetry@trunk
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Checkout Dify repository
      uses: actions/checkout@v6
      with:
        repository: stone-home/Python-RAG-Knowledge
        token: ${{ steps.get-home-stone-token.outputs.token }}
        path: dify_repo
        ref: trunk

    - name: Install dependency and generate new file
      shell: bash
      run: |
        cd dify_repo
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        poetry install
        poetry run python main.py \
        --host "${{ inputs.dify-url }}" \
        --dir "${{ inputs.target_dir_path }}"
      env:
        DIFY_API_KEY: ${{ steps.get-dify-api-token.outputs.token }}
        CF-Access-Client-Id: ${{ steps.get-cloud-username.outputs.token }}
        CF-Access-Client-Secret: ${{ steps.get-cloud-cred.outputs.token}}
