name: Workflow-PyPi Publish via Poetry

inputs:
  python-version:
    description: "Python Version"
    required: false
    default: "3.11"
  poetry-version:
    description: "Poetry Version"
    required: false
    default: "1.8.5"
  version-id:
    description: "Release name or ID"
    required: true
  github-token-path:
    description: "The path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  pypi-enable:
    description: "Enable release process"
    required: false
    default: "false"
  pypi-token-path:
    description: "The path of PyPi"
    required: false
    default: "op://DevOps/PyPi Token/credential"
  onepass-token:
    required: true
    description: "A access-token for 1password authorization"
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"

# ===========================================================================
# Required Permission
#permissions:
#  contents: read
# ===========================================================================

runs:
  using: composite
  steps:
    # 2. Set up Python & Poetry environment
    - name: Setup Python and Poetry
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-poetry@trunk
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}

    # 3. load Secrets from 1password
    - name: Configure 1Password Service Account
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get GitHub Token
      id: get-github-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    # 7. create a branch
    - name: Create Release Branch
      shell: bash
      run: |
        BRANCH_NAME="versions/${{ inputs.version-id }}"
        git config user.name "Publish Action"
        git config user.email "github@stone-bo.com"
        git checkout -b "$BRANCH_NAME"
        git push --set-upstream origin "$BRANCH_NAME"
        echo "Created branch: $BRANCH_NAME"
      env:
        GITHUB_TOKEN: ${{ steps.get-github-token.outputs.token}}

    # 8. Update version in pyproject.toml to match the tag version
    - name: Update version in pyproject.toml
      shell: bash
      run: |
        NEW_VERSION=$(echo ${{ inputs.version-id }} | sed 's/^v//') # Remove 'v' prefix if it exists
        poetry version "$NEW_VERSION"
        git add pyproject.toml
        git commit -m "chore(poetry): bumping the version to ${{ inputs.version-id }}"
        git push
    # 9. Build package
    - name: Build package
      shell: bash
      run: poetry build

    # 10. Publish the package
    - name: Get PyPi Token
      id: get-pypi-token
      if: ${{ inputs.pypi_enable == 'true' }}
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.pypi-token-path }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}
        onepass-token: ${{ inputs.onepass-token }}

    - name: Publish package to PyPI
      if: ${{ inputs.pypi_enable == 'true' }}
      shell: bash
      run: poetry publish -u __token__ -p ${{ steps.get-pypi-token.outputs.token }}
