name: Workflow-PyPi Publish via Poetry

inputs:
  python-version:
    description: "Python Version"
    required: true
    default: "3.11"
  poetry-version:
    description: "Poetry Version"
    required: true
    default: "1.8.5"
  version-id:
    description: "Release name or ID"
    required: true
  github-token-path:
    description: "The path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  pypi_enable:
    description: "Enable release process"
    required: false
    default: "false"
  pypi-token-path:
    description: "The path of PyPi"
    required: false
    default: "op://DevOps/PyPi Token/credential"
  onepass-token:
    required: true
    description: "A access-token for 1password authorization"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 2. Set up Python & Poetry environment
      - name: Setup Python and Poetry
        uses: stone-home/Action-Stone-DevOps/.github/actions/setup-poetry
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}

      # 3. load Secrets from 1password
      - name: Configure 1Password Service Account
        uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password
        with:
          onepass-token: ${{ secrets.onepass-token }}

      - name: Load credentials
        id: load-credentials
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          GITHUB_TOKEN: ${{ inputs.github-token-path }}
          PYPI_TOKEN: ${{ inputs.pypi-token-path }}

      # 7. create a branch
      - name: Create Release Branch
        shell: bash
        run: |
          BRANCH_NAME="versions/${{ inputs.version-id }}"
          git config user.name "Publish Action"
          git config user.email "github@stone-bo.com"
          git checkout -b "$BRANCH_NAME"
          git push --set-upstream origin "$BRANCH_NAME"
          echo "Created branch: $BRANCH_NAME"
      # 8. Update version in pyproject.toml to match the tag version
      - name: Update version in pyproject.toml
        shell: bash
        run: |
          NEW_VERSION=$(echo ${{ inputs.version-id }} | sed 's/^v//') # Remove 'v' prefix if it exists
          poetry version "$NEW_VERSION"
          git add pyproject.toml
          git commit -m "chore(poetry): bumping the version to ${{ inputs.version-id }}"
          git push
      # 9. Build package
      - name: Build package
        run: poetry build
      # 10. Publish the package
      - name: Publish package to PyPI
        if: ${{ inputs.pypi_enable == 'true' }}
        run: poetry publish -u __token__ -p ${{ env.PYPI_TOKEN }}
