name: "Setup NodeJS"
description: "Configures NodeJS Runtime"
inputs:
  node-version:
    description: "NodeJS version"
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: npm ci
