name: Deploy MkDocs Site
inputs:
  python-version:
    description: "Python Version"
    required: false
    default: "3.11"
  poetry-version:
    description: "Poetry Version"
    required: false
    default: "1.8.5"
  github-token-path:
    description: "The path of GitHub token"
    required: false
    default: "op://DevOps/Git PAT - StoneHome - Action/credential"
  onepass-token:
    description: "1password connect token"
    required: true
  kubernetes-mode:
    description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Python and Poetry
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-poetry@trunk
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}

    - name: Build Site
      shell: bash
      run: poetry run mkdocs build

    - name: Configure 1Password Service Account
      uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password@trunk
      with:
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Get Personal Token
      id: get-token
      uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
      with:
        secret-path: ${{ inputs.github-token-path }}
        onepass-token: ${{ inputs.onepass-token }}
        kubernetes-mode: ${{ inputs.kubernetes-mode }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ steps.get-token.outputs.token }}
        publish_branch: gh-pages
        publish_dir: ./site
