name: Deploy Hugo Site

on:
  workflow_call:
    inputs:
      hugo-version:
        required: false
        type: string
        default: "0.144.2"
      github-token-path:
        required: false
        type: string
        default: "op://DevOps/Git PAT - StoneHome - Action/credential"
    secrets:
      onepass-token:
        required: true

permissions:
  contents: read

jobs:
  hugo:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write # Needed for gh-pages deployment

    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ inputs.hugo-version }}
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies & Build
        run: |
          npm ci
          hugo --minify

      - name: Configure 1Password Service Account
        uses: stone-home/Action-Stone-DevOps/.github/actions/setup-1password
        with:
          onepass-token: ${{ secrets.onepass-token }}

      - name: Get Personal Token
        id: get-token
        uses: stone-home/Action-Stone-DevOps/.github/actions/load-github-token@trunk
        with:
          secret-path: ${{ inputs.github-token-path }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
