name: Super Linter

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  superLint:
    name: linter
    runs-on: arc-runner-large
    container: ubuntu:latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/linter
        with:
          onepass-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
