name: Workflow-Release
on:
  workflow_call:
    inputs:
      nodejs_project:
        required: false
        type: boolean
        default: false
      latex_project:
        required: false
        type: boolean
        default: false
      git_token_path:
        required: false
        type: string
        default: "op://DevOps/Git PAT - StoneHome - Action/credential"
    secrets:
      onepass_token:
        description: "A access-token for 1password authorsation"
        required: true

permissions:
  contents: read # for checkout
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v2
        with:
          # Persist the 1Password Service Account Authorization token
          # for next steps.
          # Keep in mind that every single step in the job is now
          # able to access the token.
          service-account-token: ${{ secrets.onepass_token }}

      - name: Load GitHub credentials
        id: load-credentials
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          GITHUB_TOKEN: ${{ inputs.git_token_path }}

      - name: Cache TeX Live installation
        id: cache-texlive
        if: ${{ inputs.latex_project }}
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-texlive-latest
          path: /usr/local/texlive

      # Install TeX Live everytime to restore soft links' issues after loading cache
      - name: Install TeX Live
        if: ${{ inputs.latex_project}}
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Node.js install dependencies
        if: ${{ inputs.nodejs_project }}
        run: npm ci
      - name: Node.js Build
        if: ${{ inputs.nodejs_project }}
        run: npm run build

      - run: npx semantic-release@25.0.2
        name: create a new release page and tag
        env:
          GITHUB_TOKEN: ${{ steps.load-credentials.outputs.GITHUB_TOKEN }}
