name: Super Linter

on:
  push:
    branches-ignore:
      - trunk
  pull_request:

jobs:
  superLint:
    name: linter
    #    runs-on: ubuntu-latest
    runs-on: arc-runner-large
    container:
      image: ghcr.io/super-linter/super-linter:v8.5.0
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/linter
        with:
          onepass-token: ${{ secrets.OP_ACCOUNT_TOKEN }}
