name: Trufflehog

on:
  workflow_call

jobs:
  secretCheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@3.88.2
        with:
          extra_args: --results=verified,unknown