name: Workflow - Comprehensive Gateway of Release
on:
  workflow_call:
    inputs:
      python-project:
        required: false
        type: boolean
        default: false
      nodejs-project:
        required: false
        type: boolean
        default: false
      latex-project:
        required: false
        type: boolean
        default: false
      git-token-path:
        required: false
        type: string
        default: "op://DevOps/Git PAT - StoneHome - Action/credential"
      nodejs-version:
        required: false
        type: string
        default: "22"
        description: "The version of NodeJS"
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "THe version of Python"
      poetry-version:
        required: false
        type: string
        default: "1.8.5"
        description: "The version of Poetry"
      version-id:
        required: true
        type: string
      pypi-enable:
        description: "Feature only work when python-project is true"
        required: false
        type: boolean
        default: false
      pypi-token-path:
        description: "Feature only work when python-project is true"
        required: false
        type: string
        default: "op://DevOps/PyPi Token/credential"
      kubernetes-mode:
        description: "enable kubernetes mode, meaning that this action run on a host with ARC kubernetes mode"
        required: false
        type: boolean
        default: false
    secrets:
      onepass-token:
        description: "A access-token for 1password authorsation"
        required: true

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # Required for OIDC/Trusted Publishing
jobs:
  python:
    name: Publish Python Project to PyPi
    if: inputs.python-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/publish-python@trunk
        with:
          onepass-token: ${{ secrets.onepass-token }}
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
          version-id: ${{ inputs.version-id }}
          github-token-path: ${{ inputs.git-token-path }}
          pypi-enable: ${{ inputs.pypi-enable }}
          pypi-token-path: ${{ inputs.pypi-token-path }}
          kubernetes-mode: ${{ inputs.kubernetes-mode }}
  js:
    name: Release Project to GitHub Rlease in NPM environment
    if: inputs.nodejs-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/publish-npm@trunk
        with:
          node-version: ${{ inputs.nodejs-version }}
          github-token-path: ${{ inputs.git-token-path }}
          onepass-token: ${{ secrets.onepass-token }}
          kubernetes-mode: ${{ inputs.kubernetes-mode }}
  latex:
    name: Release Project to GitHub Rlease for LaTex Documents
    if: inputs.latex-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/publish-latex@trunk
        with:
          node-version: ${{ inputs.nodejs-version }}
          github-token-path: ${{ inputs.git-token-path }}
          onepass-token: ${{ secrets.onepass-token }}
          kubernetes-mode: ${{ inputs.kubernetes-mode }}
  other:
    name: Basic Release Process
    if: inputs.python-project == false && inputs.nodejs-project == false && inputs.latex-project == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: stone-home/Action-Stone-DevOps/.github/actions/publish-basic@trunk
        with:
          github-token-path: ${{ inputs.git-token-path }}
          onepass-token: ${{ secrets.onepass-token }}
          kubernetes-mode: ${{ inputs.kubernetes-mode }}
